POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "name": "Sistemas Operacionais",
  "description": "Curso básico de sistemas operacionais que contempla conceitos básicos como o de processos e threads, gerenciamento de memória e sistemas de arquivos."
}

