GET http://localhost:8080/api/courses
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYzZmMDg1YS00M2U0LTQ2NzgtYjc4Mi05MzBmY2FkZWI5N2IiLCJyb2xlIjoiU3R1ZGVudCIsIm5iZiI6MTcxODM2OTU4NCwiZXhwIjoxNzE4Mzk4Mzg0LCJpc3MiOiIxMjMiLCJhdWQiOiIxMjMifQ.XCzEdNr2r3Oj8bNdl8e4hymPwZV8byRKKxDO4Mw0RSeFKj-53dcJI1gG7-76OlBejOgRKQ9T7U0Pft52ibZyZQ
Accept: application/json