PUT http://localhost:8080/api/courses/397bdb77-5d42-4961-aafc-bde93acf6922/cover
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="cover"; filename="curso.png"

< C:\Users\joaob\OneDrive\Área de Trabalho\curso.png

--boundary--